config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :todos
  resources :posts
  resources :activities do
    resources :comments

    collection do
      post :abandon_activity
    end

    member do
      get 'my_activities'
      get 'user_details'
      get 'by_code'
    end
  end

  resources :answers, only: :create

  namespace :admin do
    resources :answers, only: :index
  end

  get 'activities/:id' => 'activities#activity'

  # delete activity with activity ID
  get 'delete_activity/:id' => 'activities#delete_activity', as: :delete_activity
  get '/quit_experiment' => 'rewards#quit_experiment'
  get '/start_tetris' => 'rewards#start_tetris'
  get '/activity_detail/:id' => 'activities#get_activity_detail', as: :get_activity_detail
  post '/start_activity/:id' => 'activities#start_activity', as: :start_activity
  get '/abort_activity/:id' => 'activities#abort_activity', as: :abort_activity

  # secret admin code to set user as an admin
  get '/enable_admin/:code' => 'activities#enable_admin' 

  # set all default activities with admin's current activities
  get '/set_default_activities' => 'activities#set_default_activities', as: :set_default_activities
  get '/export_data' => 'activities#export_data', as: :export_data
  get '/export_user_data' => 'activities#export_user_data', as: :export_user_data
  get '/generate_code/' => 'activities#generate_code', as: :generate_code
  post '/submit_text/' => 'activities#submitText', as: :submitText
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_activity

  def create
    @comment = @activity.comments.build(comment_params)
    @comment.user_id = current_user.id
   
    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js
      end
    else
      flash[:alert] = "Check the comment form"
      render root_path
    end
  end

  def destroy
    @comment = @activity.comments.find(params[:id])
    
    # If user_id == current user id

    if @comment.user_id == current_user.id
      @comment.destroy
      puts "TESTING DESTROY"
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js
      end 
    end

  end

  private
 
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_activity
    @activity = Activity.find(params[:activity_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- Comment Partial -->

<div id="comment">
  <div class="user-name">
    <%= comment.user.user_name %>
  </div>
  <div class="comment-content">
    <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= link_to activity_comment_path(activity, comment), method: :delete , remote: true do %>
    <!-- Comment deletion bug? -->
      <span class="glyphicon glyphicon-remove delete-comment">
      </span>
    <% end %>

  <% end %>
</div>

app/views/comments/create.js.erb
// AJAX for comments

$('#comments_<%= @activity.id %>').append("<%=j render 'comments/comment', activity: @activity, comment: @comment %>");
$('#comment_content_<%= @activity.id %>').val('')

app/views/comments/destroy.js.erb
// AJAX for deleting

$('#comments_<%= @activity.id %>').html("<%= j render @activity.comments, activity: @activity, comment: @comment %>");