config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :todos
  resources :posts
  resources :activities do
    resources :comments

    collection do
      post :abandon_activity
    end

    member do
      get 'my_activities'
      get 'user_details'
      get 'by_code'
    end
  end

  resources :answers, only: :create

  namespace :admin do
    resources :answers, only: :index
  end

  get 'activities/:id' => 'activities#activity'

  # delete activity with activity ID
  get 'delete_activity/:id' => 'activities#delete_activity', as: :delete_activity
  get '/quit_experiment' => 'rewards#quit_experiment'
  get '/start_tetris' => 'rewards#start_tetris'
  get '/activity_detail/:id' => 'activities#get_activity_detail', as: :get_activity_detail
  post '/start_activity/:id' => 'activities#start_activity', as: :start_activity
  get '/abort_activity/:id' => 'activities#abort_activity', as: :abort_activity

  # secret admin code to set user as an admin
  get '/enable_admin/:code' => 'activities#enable_admin' 

  # set all default activities with admin's current activities
  get '/set_default_activities' => 'activities#set_default_activities', as: :set_default_activities
  get '/export_data' => 'activities#export_data', as: :export_data
  get '/export_user_data' => 'activities#export_user_data', as: :export_user_data
  get '/generate_code/' => 'activities#generate_code', as: :generate_code
  post '/submit_text/' => 'activities#submitText', as: :submitText
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :answers, dependent: :destroy, inverse_of: :activity

  belongs_to :user, inverse_of: :activities

  validates :user_id, presence: true

  def question
    QUESTIONS[a_id][0]
  end

  def project
    ACTIVITIES.detect { |activity| activity['Number'] == a_id.to_s }['Goal']
  end
end

app/controllers/activities_controller.rb
require 'csv'

class ActivitiesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_activity, only: [:show, :edit, :update, :destroy]
	before_action :owned_activity, only: [:edit, :update, :destroy]

  rescue_from ActionController::InvalidAuthenticityToken, with: :bad_token

	def index
	  @activities = Activity.all
	  @users = User.all
	end

	def new
	  @activity = current_user.activities.build
	end

	# Create an activity by an Admin using "New Activity" form. Not used b/c
	# Activities are imported via CSV.
	def create
	  @activity = current_user.activities.build(activity_params)

	  if @activity.save
		  flash[:success] = "Your activity has been created!"
		  redirect_to activities_path
	  else
		  flash[:alert]  = "Your new activity couldn't be created!"
		  render :new
	  end
	end

	def show
	  @activity = Activity.find(params[:id])
	end

	def edit
	end

	def update
    if @activity.update(activity_params)
      flash[:success] = "Activity updated."
      redirect_to activities_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
	end

	def destroy
	  Activity.find(params[:id]).destroy
	  redirect_to activities_path
	end

  # To display all of my activities
  def my_activities
    get_current_point_values(current_user)
    @activities = current_user.activities.order('id ASC')
  end

  # To display all of my completed activities
  def my_completed_activities
    @activities = Activity.where(user_id: params[:id], is_completed: true)
  end

  # Renders user details page
  def user_details
    @details = [current_user.score, current_user.level]
  end

  def get_activity_detail
    render json: current_user.activities.find(params[:id])
  end

  def start_activity
    qid = params[:id].to_i == 0 ? params[:qid] : current_user.activities.find(params[:id]).a_id
    create_quitter(qid, activity_start_time: Time.now.to_s)
    render nothing: true
  end

  # called when the user selects another activity without finishing the current activity
  def abandon_activity
    create_quitter(params[:a_id], activityAbortTime: Time.now.to_s)
    render nothing: true
  end

  def delete_activity
    current_user.activities.where(a_id: params[:id]).destroy_all
    render text: 'delete activity'
  end

	# Aborts the current activity and logs data into Quitter class for exporting
	# params: - :id: Id of the activity to abort.
  def abort_activity
    Time.zone = "America/Los_Angeles"

    @activity = current_user.activities.find_by(a_id: params[:id])
    @activity.update(abort_time: Time.now.to_s);

    last_quitter_record = current_user.quitters.recent.find_by!(activity_id: @activity.a_id)
    last_quitter_record.update(activityAbortTime: Time.new.to_s)

    render text: 'abort activity'
  end

  # Creates points table from CSV file "points.csv"
  def create_points_table
    Point.delete_all

    @constant_point_value = BONUS * 100 / ACTIVITIES.count

    ACTIVITIES.each do |activity|
      Point.create(activity_id: activity['Number'], state: 0, point_value: @constant_point_value, time_left: 0, condition: "constant points")
      Point.create(activity_id: activity['Number'], state: 0, point_value: 0, time_left: 0, condition: "control condition")
    end

    csv_text = File.read(Rails.root.join('app', 'assets', 'data', 'points.csv'))
    csv = CSV.parse(csv_text, :headers => true)

    ['points condition', 'monetary condition'].each do |condition|
      values = csv.map { |row| "(#{row['activity_id']}, #{row['state_id']}, #{row['point_value'].to_i}, '#{condition}')" }
      ActiveRecord::Base.connection.execute(%Q{INSERT INTO points (activity_id, state, point_value, condition) VALUES #{values.join(', ')}})
    end
  end

	# Sets default activities for an experimentee.
	# Pulls admin's todo list and initializes experimentee's account with Admin's to-do list
	# params - :current_user: The user id of the current user initializing their to-do list.
  def set_default_activities
    current_user.activities.destroy_all

    condition_names = ['monetary condition', 'length heuristic','control condition']
    #condition_names = ['control condition', 'monetary condition', 'points condition', 'constant points', 'advice', 'forced']
    #condition_nr = current_user.id % 6
    #condition_names = ['monetary condition', 'advice', 'forced']
    #condition_names = ['monetary condition x 10','advice','forced']
    condition_nr = current_user.id % condition_names.length

    current_user.update(experimental_condition: condition_names[condition_nr])

    ACTIVITIES.each do |activity|
      current_user.activities.create(
        content: activity['Name'],
        duration: activity['Duration'].to_f,
        code: SecureRandom.urlsafe_base64(8),
        a_id: activity['Number']
      )
    end

    points = get_current_point_values(current_user)

    current_user.activities.each do |activity|
      activity.update_column(:points, points[activity.a_id - 1])
    end

    redirect_to my_activities_activity_path(current_user)
  end

	# Function to render all data from activities and users for the experimenter
  def export_data
    @quitters = Quitter.all
    render json: @quitters
  end

  def export_user_data
    @users = User.all
    render json: @users
  end

  # Code generation for when users claim their payment
    # FORMAT: [activities completed] i [User Id] d [User quit] q [user Experimental condition]
  def generate_code
    @user_id = current_user.id
    #@activities = Activity.where(:user_id => @user_id)
    @activities = current_user.activities.order('a_id ASC')      
      
    @user_experimental_condition = current_user.experimental_condition
    @user_score = current_user.score
    @user_quit = current_user.is_active

    @score = "b"

    #Setting the activites Score
    @activities.each do |record|
      if record.is_completed
        @score = @score + "1"
      else
        @score = @score + "0"
      end
    end

    @score = @score + "i"

    # User ID
    @score += @user_id.to_s
    @score = @score + "d"

    #user quit
    if @user_quit
      @score += "1"
    else
      @score += "0"
    end
    @score = @score + "q"

    #User experimental Condition
    if @user_experimental_condition == "Initial condition"
      @score += "1"
    else
      @score += "0"
    end
    @score += "e"
    puts @score

    render json: @score.to_json
  end

  def by_code
    render json: current_user.activities.find_by(code: params[:id])
  end

  # TODO:
  def enable_admin
    return render(text: 'Wrong Code') if params[:code] != '9128'

    if admin = User.find_by(user_name: "Admin")
      admin.update(is_admin: true)
      create_points_table
    end

    render text: 'admin enabled'
  end

	private

	def activity_params
	  params.require(:activity).permit(:image, :content, :points, :duration, :code, :a_id)
	end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def owned_activity
    unless current_user == @activity.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

  def bad_token
    flash[:warning] = "Session expired"
    redirect_to root_path
  end

  def create_quitter(question_id, options)
    Quitter.create(options.merge(user_id: current_user.id, activity_id: question_id))
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activities.html.slim
- activities.each do |activity|
  // Insert Activity partial only if activity id matches with current logged in user
  - if current_user.id == activity.user_id
    span data-activity-id="#{activity.id}" data-question-id="#{activity.a_id}" id="activity_#{activity.id}"
      - if can_work_on_activity?(current_user.experimental_condition, activity, next_activity_by_points)
        a.activity-item#activity_select data-toggle="tab" href="##{activity.a_id}"
          = render 'activities/activityBar', activity: activity, disabled: false

      - else
        = render 'activities/activityBar', activity: activity, disabled: true

app/views/activities/_activity.html.erb
<!-- Activity partial -->
<div class="activities-wrapper">

</div>

app/views/activities/_activityBar.html.slim
css:
  .activity-completed {
    text-decoration: line-through;
  }

  .activity-completed.alert-success {
    background-color: rgb(223, 240, 216, 0.5);
    border-color: rgb(214, 233, 198, 0.5);
    color: rgb(60, 118, 61, 0.5);
  }

  .activity-completed.alert-danger {
    background-color: rgb(242, 222, 222, 0.5);
    border-color: rgb(235, 204, 209, 0.5);
    color: rgb(169, 68, 66, 0.5);
  }

  .activity-bar {
    margin: 5px;
    position: relative;
    padding-left: 0;
    height: 100%;
    box-shadow: rgba(0, 0, 0, 0.238281) 0px 1px 5px;
    border-top-left-radius: 2px 2px;
      border-top-right-radius: 2px 2px;
      border-bottom-right-radius: 2px 2px;
      border-bottom-left-radius: 2px 2px;
  }

  .activity-bar-id {
    height: 100%;
    position: relative;
    margin: 15px 5px;
    margin-left: 10px;
    font-size: 90%;
  }

  .activity-bar-content {
    padding: 15px 15px 15px 0;
    width: 70%;
    overflow: hidden;
  }

  .activity-bar.alert-danger:hover {
    cursor: pointer;
    opacity: .7;
  }

.activity-bar.alert.alert-block class=[disabled && 'alert-warning', activity.is_completed? && 'activity-completed', activity.points >= 0 ? 'alert-success' : 'alert-danger']
  - if current_user.is_admin?
    button.close.close-sm data-dismiss="alert" type="button" onclick='removeActivity(#{activity.a_id})'
      i.fa.fa-times

  span.activity-bar-id = activity.a_id

  span.activity-bar-content
    strong style="font-size: 90%;"
      = "#{activity.content}" 

    - if current_user.initial? || current_user.points? || current_user.constant_points?
      span style="float:right; font-size: 130%;"
        = activity.points
        i.fa.fa-star-o

    - elsif current_user.monetary? || current_user.length_heuristic?
      span style="float: right; font-size: 130%;"
        i.fa.fa-usd
        = '%.2f' % (activity.points / 100.0)

    - elsif current_user.monetaryX10?
      span style="float: right; font-size: 130%;"
        i.fa.fa-usd
        = '%.2f' % (activity.points / 10.0)

javascript:
  var removeActivity = function(activity_id){
    console.log("Deleting activity");
    console.log(activity_id);
    $.get('/delete_activity/' + String(activity_id), function(data) {
      console.log("deleting activity");
    });
  }

app/views/activities/_activityPanelContent.html.erb
<style>
    .external-link img {
      height: 50px;
      padding: 0 10px;
      float: left;
    }

    .external-link div {
      white-space: normal;
      text-align: left;
    }

    /*Container for buttons in the activity container*/
    .activity-functions {
        position: relative;
        width: 100%;
        margin-bottom: 0px;
        padding-left: 0;
    }

    #activity-progress-input {
      margin-top: 10px;
    }

    .experiment-game-container {
      position: relative;
      border: 1px solid #eee;
      padding: 5px;
    }

    .btn-youtube{
        background-image: <% asset_path('youtube.png') %>;
    }

    #stats {
  float: right;
  padding-left: 15px;
  padding-right: 15px;
  padding-bottom: 9px;
  padding-top: 9px;
  box-shadow: rgba(0, 0, 0, 0.2382) 0px 1px 5px;
  background-color: #dff0d8;
  border-radius: 70px;
  color: green;
    font-size: 135%;
    }

    #stats p {
      margin-bottom: 0;
    }
    #stats span {
      color: green;
    }
</style>

<div class="activity-content-wrap">
  <div class="container activity-functions">
    <div align="center" style='height:50px; overflow:hidden; width:100%;'>
      <div class='pull-left' style='width:10%;'>
        <button class="btn btn-danger" onclick="removeExperiment()" style='width:100%; line-height:48px; padding:0;'> Abort </button>
      </div>

      <div class='link-wrapper pull-left' style='font-size:1.35em; width:90%;' data-index=0 data-link-index=0></div>
    </div>

    <div class='clearfix' style="padding:20px 0; font-size:200%;">
      <strong>
        Writing Assignment <span class='activity-number'></span>
      </strong>
    </span>

    <% if current_user.points? || current_user.constant_points? %>
      <div id="stats">
        <p><strong>Level: </strong> <span class='user-level'> <%= current_user.level %></span></p>
        <p><strong>Points: </strong> <span class='user-score'> <%= current_user.score %> </span> </p>
      </div>

    <% elsif current_user.monetary? || current_user.length_heuristic? %>
      <div id="stats">
        <p><strong>Level: </strong> <span class='user-level'> <%= current_user.level %></span></p>
        <p><strong>Money: </strong> <span class='user-score'> <%= number_to_currency(current_user.score.to_f / 100) %> </span> </p>
      </div>

    <% elsif current_user.monetaryX10? %>
      <div id="stats">
        <p><strong>Level: </strong> <span class='user-level'> <%= current_user.level %></span></p>
        <p><strong>Money: </strong> <span class='user-score'> <%= number_to_currency(current_user.score.to_f / 10) %> </span> </p>
      </div>
    <% end %>
  </div>

  <div class="experiment-game-container">
    <%= form_for current_user.answers.build, html: { remote: true } do |f| %>
      <%= f.hidden_field :activity_id %>
      <div class="game-content" style="width: 100%; height: 100%; overflow: hidden;">
        <h4 style="text-align:center; line-height: 150px;">
          Please select a task to work on!
        </h4>
      </div>
      <div class='input-controls'>
        <div class='warning' id='additionalInstructions'>
            Your text should be original and of the highest quality, and you have to write at least <span id='requiredLength'>100</span> words. If you copy from a different source, then your submission will be rejected.
        </div>

        <%= f.text_area :answer, rows: 8, style: 'width:80%; margin:0 10%;' %>
        <%= f.submit 'Submit', style: 'display:block; margin:0 auto;' %>
      </div>
    <% end %>

    <div class='hint' style='display:none' id='success-message'>
      Thank you! Your response has been recorded and will be graded when you submit the HIT.
      <br>
      If your response does not meet the requirements of this assignments then you will lose some or all of your bonus.
    </div>

    <div class='warning' style='display:none' id='fail-message'>
      <b>Your response is too short. You have to elaborate your response further before your can submit this assignment.</b>
      <button class='retry-button'>Okay, I will revise my response.</button>
    </div>
  </div>
</div>

<script>
  function removeExperiment() {
    var currentId = document.getElementsByClassName('tab-pane active')[0].id;
    $(".game-content").html("<h4 style='text-align:center; margin-top: 100px;''> Task Aborted. <br/> Please select a new task! </h4>");
    $.get('/abort_activity/' + String(currentId));
  }
</script>

app/views/activities/_success_message.html.slim
p#congrats
  strong Congratulations! You have completed all of the tasks. Please navigate to "Account", click "Generate bonus code", and redeem your points on Amazon Mechanical Turk.

app/views/activities/activity.html.erb
<div class="activities-wrapper row">
  <div class="activity">
    <div class="activity-head">
    </div>
    <p class="caption">
      <%= @activity.content %>
    </p>
    <div class="text-center">
      <%= link_to "Cancel", activities_path %>
    </div>
  </div>


  
</div>

app/views/activities/edit.html.erb
<h1 class="header-text"> Edit Todo Task </h1>

<%= render 'form'  %>


<div class="text-center edit-links">
  <%= link_to "Delete Activity", activity_path(@activity), method: :delete, data: { confirm: "Are you sure you want to delete this Activity?" } %>
  |
  <%= link_to "cancel", activities_path %>
</div>

app/views/activities/index.html.erb
<section class="content">
   <div class="row">
      <div class="col-md-12">
         <!--breadcrumbs start -->
         <ul class="breadcrumb">
            <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
            <li class="active"><a href="#">Welcome</a></li>
            <li class="active">Intro</li>
         </ul>
         <!--breadcrumbs end -->
      </div>
   </div>
   <div class="row">
      <div class="col-md-12">
         <div class="description-heading">
            <h4>Welcome. </h4>


            <!-- Start hidden paragraph -->
            <div id="hiddenIntro">
               <p>Welcome to the to-do list experiment! Clicking on "My Tasks" in the menu will bring up your to-do list. When you work on these tasks is completely up to you. You can log in any time, take a break, or log out whenever you feel like it. 
               <br>
                   <p> There are 10 tasks in total and you may complete as many or as few as them as you like. The tasks belong to two separate projects. Both projects have their deadline on <strong> February 11 2019 </strong> at 12am Pacific Time (midnight). To complete a project you have to submit original, high-quality essays for all of its assignments. If you complete Project 1 but not Project 2 you earn a bonus of $20. If you complete Project 2 but not Project 1 you earn a bonus of $1.</p>

               <br>  <p> To get started, click on "Initialize To-do List" down below to bring up your to-do list, and then click "My Tasks" to get started, and then choose your first task from the to-do list on the right. </p>
            <!-- End hidden paragraph -->
               <br>
               <% if current_user.experimental_condition == "Initial condition" %>
                   <%= link_to "Initialize To-do List", set_default_activities_path(:current_user => current_user.id), :class => "btn btn-info btn-md", :id => "set_default_act_btn" %>     
               <% end %>

            </div>
         </div>
      </div>
   </div>
   <style>
      .leaderboard {
      width: 100%;
      } 
   </style>


   <% if current_user.is_admin? %>
      <div class="row">
         <div class="col-md-8 leaderboard">
            <section class="panel">
               <header class="panel-heading">
                  Users DashBoard. <strong> Visible only to Admins </strong>
               </header>
               <div class="panel-body table-responsive">
                  <table class="table table-hover">
                     <thead>
                        <tr>
                           <th>#</th>
                           <th>Subject Alias</th>
                           <th>Total Points</th>
                           <!-- <th>Client</th> -->
                           <th>Level</th>
                           <!-- <th>Price</th> -->
                           <th>Status</th>
                           <th>Is active</th>
                        </tr>
                     </thead>
                     <tbody>
                        <%  @users.each do |user| %>
                        <tr>
                           <td> <%= user.id %></td>
                           <td> <%= user.user_name %></td>
                           <td> <%= user.score %></td>
                           <td> <%= user.level %></td>
                           <td><span class="label label-danger"><%= user.experimental_condition %></span></td>
                           <td><span class="badge badge-info"><%= user.is_active %></span></td>
                        </tr>
                        <% end %> 
                     </tbody>
                  </table>
               </div>
            </section>
         </div>
      </div>

   <% end %>
</section>
<!--  -->
<!-- <h1 class="header-text"> Cognitive Tools for Self Mastery</h1> -->
<!-- <h3 style="text-align: center"> All tasks </h3> -->
<div class="activities-wrapper row">
   <% @activities.each do |activity| %>
   <!-- Insert activity partial here -->
   <%= render 'activity', activity: activity %>
   <% end %>
</div>


<script>

</script>

app/views/activities/new.html.erb
<%= render 'form'  %>

app/views/activities/show.html.erb
<!-- <div class="activities-wrapper row">
  <div class="activity">
    <div class="activity-head">
      <div class="name">
        Owen Chen
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @activity.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @activity.content %>
    </p>
  </div>
</div>
 -->

 <!-- Passing in the partials @activity variable -->
 
<%= render 'activity', activity: @activity %>

<div class="text-center edit-links">
  <!-- Checking if current user id is the same as activity of the id -->
  <% if @activity.user.id == current_user.id %>
    <div class="text-center edit-links">
      <%= link_to "Cancel", activities_path %>
      |
      <%= link_to "Edit Post", edit_activity_path(@activity) %>
    </div>
    <% else %>
      <div class="text-center edit-links">
        <%= link_to "Cancel", activities_path %>
      </div>
    <% end %>

</div>

app/views/activities/user_details.html.slim
css:
  #set_default_act_btn {
    font-size: 80%;
  }

  .user-container {
    width: 60%;
    margin-top: 50px;
    background: #ffffff;
    padding: 15px;
    box-shadow: rgba(0, 0, 0, 0.15625) 0px 1px 5px;
    border-top-left-radius: 2px 2px;
    border-top-right-radius: 2px 2px;
    border-bottom-right-radius: 2px 2px;
    border-bottom-left-radius: 2px 2px;
  }

  .user-jumbo {
    height: 100%;
    margin-bottom:0;
    box-shadow: rgba(0, 0, 0, 0.15625) 0px 1px 5px;
    border-top-left-radius: 2px 2px;
    border-top-right-radius: 2px 2px;
    border-bottom-right-radius: 2px 2px;
    border-bottom-left-radius: 2px 2px;
  }

  .export-buttons {
    margin-top: 15px;
    margin-bottom: 10px;
    margin-left: 5px;
  }

  .admin-container {
    width: 60%;
    margin-top: 50px;
    background: #ffffff;
    height: 400px;
    padding: 15px;
    border-radius: 5px;
  }

.user-container.container
  .jumbotron.user-jumbo
    h1.text-center Account & Help

    p
      div style='text-align:center;'
        strong Username: 
        = current_user.user_name

      div If you have already completed all the task your want to complete and have time to complete, then you can now generate the Bonus Code that you can paste into our exit survey HIT on Amazon Mechanical Turk. If you would like to contact the experimenter then please click the Contact button. If you want to learn more about the purpose of the experiment, then you can click the About button. Finally, if you want to quit the experiment for good, then you can click the Quit Experiment button.

      - if current_user.points?
        .text-center
          strong Score: 
          = current_user.score

        .text-center
          strong Level: 
          = current_user.level

      - elsif current_user.monetary?
        .text-center
          strong
            | Money Earned: 
            i.fa.fa-usd
          = current_user.score.to_f / 100
          | 0

      - elsif current_user.monetaryX10?
        .text-center
          strong
            | Money Earned: 
            i.fa.fa-usd
          = current_user.score.to_f / 100
          | 0

        .text-center
          strong Level: 
          = current_user.level

    p.text-center
      a.btn.btn-primary.btn-lg data-toggle='modal' href='#myModal3' Contact

  .row.export-buttons
    - if current_user.is_admin?
      a.btn.btn-warning.btn-md data-toggle='modal' href='#myModal2' style='font-size:80%;' Export Experiment Code
      a.btn.btn-success data-toggle='modal' href='#myModal' style='font-size:80%;' About this Experiment

    - else
      a.btn.btn-warning.btn-md.generate-bonus-code-btn data-toggle='modal' href='#myModal2' style='font-size:80%;' Generate Bonus Code
      |  
      a.btn.btn-success data-toggle='modal' href='#myModal' style='font-size:80%;' About this Experiment
      |  
      a.btn.btn-danger.btn-md.generate-quit-code-btn data-toggle='modal' href='#myModal4' style='font-size:80%;' Quit Experiment

    .modal.fade#myModal tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'
      .modal-dialog
        .modal-content
          .modal-header
            button.close type='button' data-dismiss='modal' aria-hidden='true' ×
            h4.modal-title About this Experiment

          .modal-body
            p This HIT is a psychology experiment being conducted by Dr. Falk Lieder, a former graduate student in Professor Tom Griffiths’s Computational Cognitive Science Lab at the University of California, Berkeley. This web application was built by Owen Chen, a research assistant under Falk Lieder.
            p This study is designed to investigate the effects of different types of digital to-do list tools on productivity and motivation.
            p Your participation in this research is voluntary. You may refrain from answering any questions that make you uncomfortable and may quit the study at any time without penalty.

          .modal-footer
            button.btn.btn-default data-dismiss='modal' type='button' Close

    .modal.fade#myModal3 tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'
      .modal-dialog
        .modal-content
          .modal-header
            button.close type='button' data-dismiss='modal' aria-hidden='true' ×
            h4.modal-title Contact Information

          .modal-body
            p If you have any questions about the study, feel free to contact Falk Lieder. He can be reached at re-mturk@tuebingen.mpg.de. <br><br> If you have concerns about your rights as a participant in this experiment, please contact UC Berkeley's Committee for Protection of Human Subjects at (510) 642-7461 or subjects@berkeley.edu.”

          .modal-footer
            button.btn.btn-default data-dismiss='modal' type='button' Close

    .modal.fade#myModal4 tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'
      .modal-dialog
        .modal-content
          .modal-header
            button.close type='button' data-dismiss='modal' aria-hidden='true' ×
            h4.modal-title Quitting Experiment

          .modal-body
            p You are free to quit the experiment at any time. If you decide to quit you will not be able to rejoin the experiment later and you will receive only $3 for each hour's worth of completed assignments. 
            | Your code is:
            br
            strong#quit_code
            br
            br
            p If you choose to quit, please copy and paste or write down this bonus code and enter it into the "Compensation for To-Do List Experiment” HIT by requester “MPRG for Rationality Enhancement”. 

          .modal-footer
            button.btn.btn-default data-dismiss='modal' type='button' Cancel
            a.btn.btn-info.btn-md href='/quit_experiment' role='button' Confirm

    .modal.fade#myModal2 tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'
      .modal-dialog
        .modal-content
          .modal-header
            button.close type='button' data-dismiss='modal' aria-hidden='true' ×
            h4.modal-title Export Code

          .modal-body
            - if current_user.points?
              | Congratulations!
            - elsif current_user.monetary?
              | Congratulations! 
              
            - elsif current_user.monetaryX10?
              | Congratulations!
              
            br
            br
            | Your bonus code is:
            br
            strong#export_code
            br
            p Please go to MTurk, find the HIT called "Compensation for To-Do List Experiment" by the requester "MPRG for Rationality Enhancement". If you cannot find the HIT right away, then please remove all search filters and then try again. If you still cannot find the HIT, then send us an email at re-mturk@tuebingen.mpg.de and we will look into it. Once you have found the HIT, fill out its exit survey and enter your bonus code there. Thank you for participating in our study! We hope you had a good time.

          .modal-footer
            button.btn.btn-default data-dismiss='modal' type='button' Close

- if current_user.is_admin?
  .admin-container.container
    h3 Admin controls
    p This is only visible to users with "Admin status." Options to set the default experimental activities and to export all user and activity data.
    h5 Instructions for facilitating activities for an admin:

    ul
      li Add activities with "New Activity" page, viewable only through admin access. This can be only granted if username is "Admin", and entering "/enable_admin/9128"
      li Add up to max 10 activities, with correct content title, duration, score, completion code, and activity number
      li Instruct experimentee's to create an account, click their account, and set their activities to get all the activities that an admin as set

    br
    = link_to 'Export Data', export_data_path, class: 'btn btn-warning btn-md', id: 'export_data_btn'
    = link_to 'Export User Data', export_user_data_path, class: 'btn btn-success btn-md', id: 'export_user_data_btn'
    = link_to 'Export Answers', admin_answers_path(format: :json), class: 'btn btn-success btn-md', id: 'export_user_data_btn'

javascript:
  $('.generate-bonus-code-btn').on('click', function() {
    console.log('Generating code');

    $.get('/generate_code', function(data) { $('#export_code').html(data) });
  });

  $('.generate-quit-code-btn').on('click', function() {
    console.log('Generating code for quitting');

    $.get('/generate_code', function(data) { $('#quit_code').html(data) });
  });