config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :todos
  resources :posts
  resources :activities do
    resources :comments

    collection do
      post :abandon_activity
    end

    member do
      get 'my_activities'
      get 'user_details'
      get 'by_code'
    end
  end

  resources :answers, only: :create

  namespace :admin do
    resources :answers, only: :index
  end

  get 'activities/:id' => 'activities#activity'

  # delete activity with activity ID
  get 'delete_activity/:id' => 'activities#delete_activity', as: :delete_activity
  get '/quit_experiment' => 'rewards#quit_experiment'
  get '/start_tetris' => 'rewards#start_tetris'
  get '/activity_detail/:id' => 'activities#get_activity_detail', as: :get_activity_detail
  post '/start_activity/:id' => 'activities#start_activity', as: :start_activity
  get '/abort_activity/:id' => 'activities#abort_activity', as: :abort_activity

  # secret admin code to set user as an admin
  get '/enable_admin/:code' => 'activities#enable_admin' 

  # set all default activities with admin's current activities
  get '/set_default_activities' => 'activities#set_default_activities', as: :set_default_activities
  get '/export_data' => 'activities#export_data', as: :export_data
  get '/export_user_data' => 'activities#export_user_data', as: :export_user_data
  get '/generate_code/' => 'activities#generate_code', as: :generate_code
  post '/submit_text/' => 'activities#submitText', as: :submitText
end

app/views/layouts/_navbar.html.slim
nav.navbar.nav-left
  .navbar-header
    .navbar-brand
      = link_to "ToDo List Experiment", root_path

  .nav-body
    .user-section
      .user-panel
        .pull-left.image
          img.img-circle#avatar src="#{asset_path('avatar.png')}" alt='User Image'

        .pull-left.info#user-description
          - if user_signed_in?
            h4#user_name = current_user.user_name

            - if current_user.experimental_condition == "Initial condition"
              i.fa.fa-circle.text-success
              br
              i.fa.fa-circle.text-info

            - elsif current_user.experimental_condition == "points condition" || current_user.experimental_condition == "constant points"
              i.fa.fa-circle.text-success
              span style="font-size:150%"
                strong
                  |  Level: 
                  span.user-level = current_user.level

              br

              i.fa.fa-circle.text-info
              span style="font-size:150%"
                strong
                  |  Score: 
                  span.user-score = current_user.score

            - elsif current_user.monetary? || current_user.length_heuristic?
              i.fa.fa-circle.text-success
              span style="font-size:150%"
                strong
                  |  Level: 
                  span.user-level = current_user.level

              br

              i.fa.fa-circle.text-info
              span style="font-size:125%"
                strong
                  |  Money: 
                  span.user-score = number_to_currency(current_user.score.to_f / 100)


            - elsif current_user.experimental_condition == "monetary condition x 10"
              i.fa.fa-circle.text-success
              span style="font-size:150%"
                strong
                  |  Level: 
                  span.user-level = current_user.level

              br

              i.fa.fa-circle.text-info
              span style="font-size:125%"
                strong
                  |  Money: 
                  span.user-score = number_to_currency(current_user.score.to_f / 10)

            - else
              br
              br
              br

            - if current_user.experimental_condition == "Initial condition"
              span

            - elsif ['control condition', 'advice', 'forced'].include?(current_user.experimental_condition)
              span

            - else
              br
              i.fa.fa-circle-o
              span.level-description style="font-size:125%"
                |  #{current_user.level_description}

          - else
            h5 Please log in

    br
    br

    div
      ul.nav.nav-custom-list
        - if user_signed_in?
          - if current_user.is_admin?
            li
              = link_to new_activity_path do
                i.fa.fa-dashboard
                span  New Activity

          li
            = link_to my_activities_activity_path(current_user) do
              i.fa.fa-gavel
              span  My Tasks

          li
            = link_to user_details_activity_path(current_user) do
              i.fa.fa-globe
              span  Account

          li
            = link_to destroy_user_session_path, method: :delete do
              i.fa.fa-glass
              span  Logout

        - else
          li.active
            = link_to new_user_session_path do
              i.fa.fa-globe
              span  Log in

          li
            = link_to new_user_registration_path do
              i.fa.fa-glass
              span  Register

javascript:
  $("ul.nav li").click(function(){
    $("ul.nav li").removeClass("active");
    $(this).addClass("active");
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo List Experiment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
    window.links = <%== LINKS.to_json %>;
    window.linkImages = [
      ['tetris', 'https://psi.is.tuebingen.mpg.de/experiments/ToDoAppImg/tetris.jpg'],
      ['youtube', 'https://psi.is.tuebingen.mpg.de/experiments/ToDoAppImg/youtube.png'],
      ['reddit', 'https://psi.is.tuebingen.mpg.de/experiments/ToDoAppImg/reddit.jpg'],
      ['news', 'https://psi.is.tuebingen.mpg.de/experiments/ToDoAppImg/news.png']
    ];
  </script>
  <!-- Resources on other origins must be CORS-enabled. -->
</head>
<body>

<div class="nav-left-container">
	<%= render 'layouts/navbar' %>
</div>

<div class="app-container">
	            <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top top-nav" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>


                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->

                        <li class="dropdown tasks-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-tasks"></i>
                                <% if user_signed_in? %>
                                    <span class="label label-danger"><%= current_user.sign_in_count %></span>
                                <% end %>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- Change this later -->
                                <% if user_signed_in? %>
                                    <li class="header">You have 10 tasks</li>
                                <% end %>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        <li><!-- Task item -->
                                        </li><!-- end task item -->
				    </ul>
                                <li class="footer">
                                    <a href="#"></a>
                                </li>
                            </ul>
                        </li>
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
			    				<% if user_signed_in? %>
			    					<span> <%= current_user.user_name %> <i class="caret"></i></span>
				    			<% else %>
				    				<span> Log In <i class="caret"></i></span>
				    			<% end %>	
                            </a>
                            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                                <li class="dropdown-header text-center">Account</li>

                                <li>
                                </li>

                                <li class="divider"></li>

                                    <% if user_signed_in? %>
                                    <li>
                                        <%= link_to user_details_activity_path(current_user) do %>
                                        <i class="fa fa-user fa-fw pull-right"></i> <span> Profile </span>
                                        <% end %>

                                        <a data-toggle="modal" href="#modal-user-settings">
                                        <i class="fa fa-cog fa-fw pull-right"></i>
                                            Settings
                                        </a>
                                        </li>

                                        <li class="divider"></li>

                                        <li>
                                            <%= link_to destroy_user_session_path, method: :delete do %>
                                                <i class="fa fa-ban fa-fw pull-right"></i><span> Logout </span>
                                            <% end %>
                                            <!-- <a href="#"><i class="fa fa-ban fa-fw pull-right"></i> Logout</a> -->
                                        </li>
                                    <% else %>
                                        <li>
                                            <a data-toggle="modal" href="#modal-user-settings">
                                                <i class="fa fa-cog fa-fw pull-right"></i>
                                                    Please Log In
                                            </a>
                                        </li>
                                    <% end %>                                       
                                    </ul>
                                </li>
                            </ul>
                        </div>        
    </nav>
	<%= yield %>

	<p class="notice" style="font-style='bold'; text-align: center;"><%= notice %></p>
	<p class="alert" style="font-style='bold'; text-align: center;"><%= alert %></p>


</div>






</body>
</html>